### ISSUE TITLE
官网文档中  自动安装器使用方法  访问404

### ISSUE THREAD

**Issue by eya46** [infstellar/genshin_impact_assistant#100]
位置
https://genshinimpactassistant.github.io/GIA-Document/#/?id=快速安装

👇
## 快速安装
请参见[GIA Launcher自动安装器使用方法](https://genshinimpactassistant.github.io/GIA-Document/#/install)。
👆

https://genshinimpactassistant.github.io/GIA-Document/#/install

**Comment by eya46** [comment]
擦，里面除了外链，咋全是404

**Comment by infstellar** [comment]
怪事

**Comment by infstellar** [comment]
重新生成了一下 好像好了 试试

**Comment by eya46** [comment]
> 怪事

https://genshinimpactassistant.github.io/GIA-Document/#/
后面加个zh_CN/就正常了...怪
https://genshinimpactassistant.github.io/GIA-Document/#/zh_CN/
要不把[README.md](https://github.com/infstellar/genshin_impact_assistant/blob/main/README.md)里面的改下把

**Comment by moulai** [comment]
是的，要有 zh_CN 或者 en_US，根目录没有这文件的。得改一下README里面的链接为绝对链接。 @infstellar

**Comment by moulai** [comment]
已修复。

**Comment by infstellar** [comment]
@moulai 
首页怎么跳转呢⊙(・◇・)？
如果首页跳转无法实现 我就改一下翻译生成的程序 把zh_CN复制给源目录一份(

**Comment by moulai** [comment]
> @moulai 首页怎么跳转呢⊙(・◇・)？ 如果首页跳转无法实现 我就改一下翻译生成的程序 把zh_CN复制给源目录一份(

想办法搞定了，详见这个commit：https://github.com/GenshinImpactAssistant/GIA-Document/commit/e15391f509a537bc778dbbe667c0ef70d2ef8abc

**Comment by eya46** [comment]
忘了关了，关
