### ISSUE TITLE
[需要帮助]自动寻路时移动视角的频率有些鬼畜

### ISSUE THREAD

**Issue by 1004452714** [infstellar/genshin_impact_assistant#150]
在自动打地脉花和自定义采集任务时的寻路，会出现频繁左右晃动转向，一秒要晃2-4次左右，这是正常现象吗？而且走的很慢。

**Comment by seriaati** [comment]
影片在此：https://streamable.com/8c7rlj
轉的我眼睛都花了還沒走到，我以為是滑鼠 DPI 的問題，但調低了也沒有變正常。
全程都是讓腳本操作。

**Comment by seriaati** [comment]
秘境也是一樣的問題，進入後就開始瘋狂自轉。

**Comment by infstellar** [comment]
> 秘境也是一樣的問題，進入後就開始瘋狂自轉。

是不是windows11？看看 https://genshinimpactassistant.github.io/GIA-Document/#/FAQ

**Comment by seriaati** [comment]
是 Windows 11 沒錯，但是已經打開「不使用窗口化遊戲優化」了

**Comment by 1004452714** [comment]
https://streamable.com/vhrhej  
补个视频，视频中目的地是左下角的每日委托，虽然晃的幅度很大，但大体方向是是对的。有时切换窗口再切回去可以正常走一会，然后又恢复摇头状态，具体请看视频的1分13秒之后

**Comment by infstellar** [comment]
试着修了一下，看看有没有用

**Comment by infstellar** [comment]
> 是 Windows 11 沒錯，但是已經打開「不使用窗口化遊戲優化」了

SMAA抗锯齿开了吗

**Comment by 1004452714** [comment]
> 试着修了一下，看看有没有用

git pull完试了一下，还是疯狂摇头
![image](https://github.com/infstellar/genshin_impact_assistant/assets/28773469/f5b72b52-6c95-4b54-968e-252188822caf)
开发的系统环境是win10吗，一会装个win10试试  不知道双显示器有没有影响。

**Comment by 1004452714** [comment]
> 试着修了一下，看看有没有用

感觉是win11的问题

换了win10使用单显示器1920*1080，全屏游戏可以正常寻路。
然后返回win11使用相同显示器相同设置的情况下，依然疯狂摇头。

不知道有没有其他使用win11的小伙伴可以正常使用

**Comment by 1004452714** [comment]
win11下，在游戏设置里的：控制-镜头-镜头水平灵敏度，数值改为1好像可以解决。目前测试了两天不会摇头了。

**Comment by infstellar** [comment]
猛修了一波，下次更新之后如果还有bug再反馈~

**Comment by Pevernow** [comment]
> 猛修了一波，下次更新之后如果还有bug再反馈~

还有bug，也是win11，没开窗口化
但是开了gia设置里的全屏无边框选项了
也是一直摇头不走直线。
还有如果一个点采集不到东西就会一直原地打转，阻塞了。

**Comment by infstellar** [comment]
可以试试 校正角度旋转参数 有没有用
最好在蒙德 风起地那里，离神像一定距离的地方开始

**Comment by 1004452714** [comment]
> 可以试试 校正角度旋转参数 有没有用 最好在蒙德 风起地那里，离神像一定距离的地方开始

https://streamable.com/1yw5hm   这样是正常的吗？
[2024-08-11.log](https://github.com/user-attachments/files/16570386/2024-08-11.log)   
灵敏度开1晃动幅度小，但会一直抖。
开3会顺时针转90度左右，抖一抖再逆时针90度转回来，继续抖。 

 平时寻路的时候偶尔也会左右摇头，但不至于完全无法寻路。有需要的话有时间录个视频。

**Comment by infstellar** [comment]
正常的，这个校正需要一段时间

**Comment by 1004452714** [comment]
> 正常的，这个校正需要一段时间

一般需要多久，今天试了下10分钟还在摇头
[2024-08-18.log](https://github.com/user-attachments/files/16645769/2024-08-18.log)

**Comment by infstellar** [comment]
我在win11的电脑上复现了这个bug，很奇怪，如果开DEBUG模式就不会出现，我怀疑是电脑性能太好引起的

**Comment by infstellar** [comment]
可以试试在genshin_impact_assistant目录下添加cvdebugmode.giamode文件（不需要写入内容）看看能不能变正常
@1004452714 @Pevernow 可以的话发一下电脑配置看看🥰

**Comment by 1004452714** [comment]
> 可以试试在genshin_impact_assistant目录下添加cvdebugmode.giamode文件（不需要写入内容）看看能不能变正常 @1004452714 @Pevernow 可以的话发一下电脑配置看看🥰

b760m
i5-13400f   
gtx4060ti  8G
32G D4 3200
固态 SN550
win11专业版 23h2-22631.3880

**Comment by infstellar** [comment]
更新了，试试新版本有没有解决

**Comment by 1004452714** [comment]
> 更新了，试试新版本有没有解决

解决了！

测试了两次不同的每日委托寻路，
平时要把水平灵敏度改为1才能维持寻路正常，
现在即使灵敏度3也不会摇头了，非常稳
