### ISSUE TITLE
[help wanted 需要帮助] dev-tool中video2path.py运行报错

### ISSUE THREAD

**Issue by 1004452714** [infstellar/genshin_impact_assistant#151]
[[GIA] 委托脚本编写教程与演示](https://www.bilibili.com/video/BV1Lu411W71q)   
按照上边的视频里操作的，
开始播放视频按a,选择ID，这一步正常。关键的是在按下“]”键之后会自动暂停，提示“press any key to continue.”，再按空格就报错了。我需要怎么解决这个问题？
![pic_2024-03-17_15-11-47](https://github.com/infstellar/genshin_impact_assistant/assets/28773469/78d38ed2-3d2a-43d4-834d-40a72a87ec25)

附视频

https://github.com/infstellar/genshin_impact_assistant/assets/28773469/1440ec8b-27fb-4525-a863-0177cdda878a

**Comment by 1004452714** [comment]
在报错的minimap.py里添加了一行
`from source.device.alas import utils as UTS`
把报错的这行
`area = area_pad(get_bbox(image, threshold=128), pad=-1)`
改成
`area = area_pad(UTS.get_bbox(image, threshold=128), pad=-1)`
算是临时解决了，水平不够不清楚自己哪里搞错了= =

**Comment by 1004452714** [comment]
感觉像是bug

source\map\detection\minimap.py文件中导入的模块中存在同名函数
`from source.map.detection.utils import *
from source.util import *
`
都有`get_bbox()`函数

**Comment by 1004452714** [comment]
感觉像是bug？ 
`source\map\detection\minimap.py`里`area = area_pad(get_bbox(image, threshold=128), pad=-1)`这一行中，
根据参数`threshold`推测想要调用`source\device\alas\utils.py`里的`get_bbox(image, threshold=0)`

但`get_bbox()`这个函数被这句`from source.util import *`导入的同名函数顶掉了
所以去调用了`source\util.py`里的`get_bbox(image, black_offset=15)`导致报错

![image](https://github.com/infstellar/genshin_impact_assistant/assets/28773469/d71b1a7b-5737-4e83-b20e-ed8ce5459fe6)
![image](https://github.com/infstellar/genshin_impact_assistant/assets/28773469/bd8dc76c-96d9-4531-92c0-2ae29e94160c)

**Comment by infstellar** [comment]
修了~
