### ISSUE TITLE
副本自动战斗的策略提议

### ISSUE THREAD

**Issue by Zhuazizizi** [infstellar/genshin_impact_assistant#155]
也许可以添加一种新的策略，或者干脆将将索敌功能的开关交于用户选择，以此优化自动索敌队伍的体验
比如我选用一队 芙宁娜 千织 阿贝多 神子 草神 奥兹 这类自动索敌角色，在此种队伍中只需要角色按部就班的施放脱手技能和盾奶技能就能稳定通过（可以加个在原地左右闪避躲一点攻击，添加副本时间过长重新启动索敌或往 副本中央/树 靠近来避免角色和怪呆在副本俩个角落永不相见的情况），这可以有效避免因为未知原因导致索敌失败反复执行索敌发呆导致的翻车
（好吧其实就是我芙宁娜队伍无限索敌实在受不了了，给她选成盾角色虽然会切出来放e了，但反复索敌期间逛街死掉的概率太高了，求求你让我关了索敌叭，让我往树那跑着丢技能就好了

**Comment by infstellar** [comment]
无限索敌是什么情况，有没有视频康康（

**Comment by Zhuazizizi** [comment]
> 无限索敌是什么情况，有没有视频康康（

其实就是这个issue提到的识别问题 https://github.com/infstellar/genshin_impact_assistant/issues/112#issue-1918521778 他会原地转动视角索敌 找不着后走两步 然后重复原地转动视角，我也将镜头默认距离拉到最远了，但没多大改善，
因此我才选了芙宁娜这种召唤角色可以有效防超时，只剩下索敌期间有时会因为站原地吃满伤害挂掉（枫丹天赋本那俩球），就想着如果可以放弃索敌直接利落的丢技能的策略也许更好，也不用去研究到底为啥识别不到那些怪了

**Comment by infstellar** [comment]
也是枫丹副本吗？我看看枫丹的怪是不是有不同

**Comment by Zhuazizizi** [comment]
> 也是枫丹副本吗？我看看枫丹的怪是不是有不同

啊对，基本都是枫丹本的事，圣遗物本 罪祸的终末 的最后俩只怪，圣遗物本 临瀑之城 的最后俩只怪，枫丹天赋本 苍白的遗荣 ，武器材料本 深潮的余响 全程。

**Comment by xoipz** [comment]
无限索敌出现的原因可能是因为红色血条的宽度太少了，导致找不到吧。
目前我的解决方案是，将芙宁娜加入队伍中，修改assets/characters_data/characters_parameters.json里关于芙宁娜的部分，把他的战斗策略改为“盾”，这样他的作战优先级就会提高了
即
"Furina": {
        "E_short_cd_time": 20,
        "E_long_cd_time": 20,
        "Elast_time": 30,
        "Epress_time": 2,
        "Qcd_time": 15,
        "Qlast_time": 18,
        "tactic_group": "e?e:none;q?q:none;",
        "vision": "Hydro",
        "trigger": "e_ready",
        "position": "Shield"
    },
这个只能在打副本的时候好用，缺点就是一开始开怪的时候可能会导致先开芙宁娜的e然后再开钟离的盾导致被打。
对了，我的常用挂机角色为：钟离、芙宁娜、瑶瑶、雷电将军

**Comment by infstellar** [comment]
可能是血太厚了？加一个索敌期间平A可能会好一点(

**Comment by infstellar** [comment]
钟离的柱子有没有挡住血条？我测试的时候是这个原因导致无限索敌 @xoipz @Zhuazizizi

**Comment by xoipz** [comment]
1、挡着血条的时候会触发索敌
2、苍白的遗荣、打机器或大型狂蔓隙境原体到残血（就3/100血左右）时，有一定的概率触发无限索敌（5把遇到1把这样，好像）
![image](https://github.com/infstellar/genshin_impact_assistant/assets/85264015/f857ef7f-c880-4f87-b452-07a3b1d3c4fa)
等有时间，我将我做的修改关掉，然后录制成视频给你看看。
测试人物：宵宫、钟离、雷电将军、瑶瑶。这样的组合应该更容易触发无限索敌情况

**Comment by xoipz** [comment]
我打的是草本，在视频开始时已经出现索敌失败了，但因为钟离有大招所以这把打赢了。如果没有大招，会出现一直索敌
链接：https://pan.baidu.com/s/1HfCR3JyDrNKgvRBzMKUceA 
提取码：hbd7

**Comment by xoipz** [comment]
我压缩了两遍视频，希望这个视频有用
链接：https://pan.baidu.com/s/1d6kmr6LGJBwsCb7iX7StDQ 
提取码：oqsl
@infstellar

**Comment by infstellar** [comment]
> 我压缩了两遍视频，希望这个视频有用 链接：https://pan.baidu.com/s/1d6kmr6LGJBwsCb7iX7StDQ 提取码：oqsl @infstellar

你的队伍里面有没有角色定位是Main，索敌的时候他能打点输出

**Comment by infstellar** [comment]
你这个抗锯齿是smaa吗 @Zhuazizizi

**Comment by Zhuazizizi** [comment]
> 你这个抗锯齿是smaa吗 @Zhuazizizi 

刚刚看了下居然是fsr2。应该是什么时候改中画质但没注意抗锯齿也被动了。改成smaa后一切正常了，现在什么毛病都没了。
原来一直都是我自己的问题，折腾了那么久实在抱歉。
