### ISSUE TITLE
setup.py无法导入installer_setup

### ISSUE THREAD

**Issue by CourantEnCourant** [infstellar/genshin_impact_assistant#158]
https://github.com/infstellar/genshin_impact_assistant/blob/19d4e8f0b7a4270b805dc52884a1b600303fc421/setup.py#L13

如标题。我在通过源代码安装时，在python setup.py这个步骤报错，显示没有installer_setup这个模组。而在repository的根目录下确实没有名为installer_setup.py的文件。

**Comment by infstellar** [comment]
感谢反馈，下次更新修复(｀･ω･´)

**Comment by infstellar** [comment]
应该已经修复了~
