### ISSUE TITLE
[可能是bug]video2path功能，在枫丹地区，从【露景泉传送锚点】到【冰封组曲】的路线，识别不准确

### ISSUE THREAD

**Issue by 1004452714** [infstellar/genshin_impact_assistant#167]
git pull的仓库main分支最新版本，submodule也update过了
试过走这三条路线，总共录了6遍以上的视频并v2p生成路线，每次都没有按路线走，歪的很离谱。
![image](https://github.com/user-attachments/assets/b3b21a0c-30ff-47ae-bf11-6840e2aff7e8)
用video2path识别视频时，疯狂提示坐标偏移过大。
运行tlpp文件夹里生成的py文件，行走的路线也不对

日志、生成的json和py文件，以及录制的路线视频
[log.log](https://github.com/user-attachments/files/16318051/log.log)
[ICE20240720082918i0.json](https://github.com/user-attachments/files/16318052/ICE20240720082918i0.json)
[ICE20240720082918i0.py.txt](https://github.com/user-attachments/files/16318055/ICE20240720082918i0.py.txt)
https://streamable.com/bx12qu

**Comment by 1004452714** [comment]
[log.log](https://github.com/user-attachments/files/16311426/log.log)
[冰.20240719194520i0.pydict.txt](https://github.com/user-attachments/files/16311434/20240719194520i0.pydict.txt)

录制过程的视频：
 - https://streamable.com/9659wd

另外还有个小问题：
 - 起始点的坐标跟之前的版本对比太多了，不好选。

**Comment by 1004452714** [comment]
move_along(tlpp)的视频演示
 - https://streamable.com/xrjv5y

```
from source.commission.commission import *


tlpp = {'name': '', 'time': '', 'start_position': [-6183.8488, -8517.8784]，省略}

class test(Commission):
    def __init__(self):
        super().__init__("", [], is_CFCF=True, is_TMCF=True)
        
    def exec_mission(self):
        self.move_along(tlpp)

        
if __name__ == '__main__':
    execc = test()
    execc.start()
```

**Comment by 1004452714** [comment]
突然发现本地main分支跟踪的是dev分支，我是傻逼 ￣□￣｜｜

**Comment by 1004452714** [comment]
.

**Comment by 1004452714** [comment]
用空荧路线生成自定义路线，后半段路程也会乱跑
![image](https://github.com/user-attachments/assets/ab28341b-0796-4f88-a862-81acafdeb223)
![image](https://github.com/user-attachments/assets/30510e0e-4410-470a-bf15-2b7d97dfba6a)

空荧地图的线段json
`{"curveName":"新的画布","curve_list":[{"lineName":"新的线条","curve_poi":[{"x":-4802.175,"y":3339.70386,"z":0.0},{"x":-4802.04736,"y":3340.08643,"z":0.0},{"x":-4801.66455,"y":3341.234,"z":0.0},{"x":-4801.792,"y":3340.85132,"z":0.0},{"x":-4801.66455,"y":3341.234,"z":0.0},{"x":-4822.44531,"y":3321.91919,"z":0.0},{"x":-4884.788,"y":3263.97485,"z":0.0},{"x":-4864.00732,"y":3283.28955,"z":0.0},{"x":-4884.788,"y":3263.97485,"z":0.0},{"x":-4892.94727,"y":3264.42114,"z":0.0},{"x":-4917.426,"y":3265.75977,"z":0.0},{"x":-4909.2666,"y":3265.31348,"z":0.0},{"x":-4917.426,"y":3265.75977,"z":0.0},{"x":-4950.31836,"y":3298.77979,"z":0.0},{"x":-5048.99561,"y":3397.83936,"z":0.0},{"x":-5016.103,"y":3364.81934,"z":0.0}]}]}`

上边json生成的任务
```
from source.mission.template.mission_just_collect import MissionJustCollect

META={'name': {'zh_CN': '1'}, 'author': '2', 'tags': {'zh_CN': ['采集'], 'en_US': ['Collect']}, 'local_edit_mission': '1', 'description': '3', 'note': '4'}
kyt2m_default_value = {'start_position': [-6403.01, -8285.56], 'end_position': [-6773.24, -8372.76], 'position_list': [{'id': 1, 'motion': 'ANY', 'position': [-6403.01, -8285.56], 'special_key': None}, {'id': 2, 'motion': 'ANY', 'position': [-6402.25, -8287.85], 'special_key': None}, {'id': 3, 'motion': 'ANY', 'position': [-6526.93, -8171.96], 'special_key': None}, {'id': 4, 'motion': 'ANY', 'position': [-6575.89, -8174.64], 'special_key': None}, {'id': 5, 'motion': 'ANY', 'position': [-6773.24, -8372.76], 'special_key': None}], 'break_position': [[-6403.01, -8285.56], [-6402.25, -8287.85], [-6526.93, -8171.96], [-6575.89, -8174.64], [-6773.24, -8372.76]], 'time': '', 'additional_info': {'kyt2m_version': '1.0', 'pickup_points': []}, 'adsorptive_position': [], 'generate_from': 'kyt2m v1.0'}

class MissionMain(MissionJustCollect):
    def __init__(self):
        super().__init__(kyt2m_default_value, "kyt2m_default_name")

if __name__ == '__main__':
    mission = MissionMain()
    mission.start()
```

**Comment by infstellar** [comment]
试试新的那个路径记录功能呢，https://genshinimpactassistant.github.io/GIA-Document/#/zh_CN/dev/record_path
这个视频转路劲没有地图全局匹配，比较费劲，等CVAT做好之后我再优化一下这个功能（）

**Comment by infstellar** [comment]
乱跑是怎样的

**Comment by 1004452714** [comment]
> 试试新的那个路径记录功能呢，https://genshinimpactassistant.github.io/GIA-Document/#/zh_CN/dev/record_path 这个视频转路劲没有地图全局匹配，比较费劲，等CVAT做好之后我再优化一下这个功能（）

好，我去试试



> 乱跑是怎样的 草，枫丹没解锁测不了，我先玩一波O（

录制的不同路线，乱跑的方向也不同  黑线是乱跑的路线，甚至有的路线一开始到达传送点 直接左拐爬柱子上了

![image](https://github.com/user-attachments/assets/9d78a7aa-50f3-4a59-9b56-0b7380b88375)

**Comment by 1004452714** [comment]
> 试试新的那个路径记录功能呢，https://genshinimpactassistant.github.io/GIA-Document/#/zh_CN/dev/record_path 这个视频转路劲没有地图全局匹配，比较费劲，等CVAT做好之后我再优化一下这个功能（）

记录路径跟v2p生成的效果一样，还是会乱跑。

**Comment by infstellar** [comment]
找到问题了，没有把这片地方添加为城区
把requirements.txt的gimapdev版本改成gimapdev==4.6.3，然后更新一下再试试

**Comment by 1004452714** [comment]
> 找到问题了，没有把这片地方添加为城区 把requirements.txt的gimapdev版本改成gimapdev==4.6.3，然后更新一下再试试

走到NPC附近有时不准确了，可能被boss的圆圈影响了？先这样凑合用了。

还有个问题：
https://genshinimpactassistant.github.io/GIA-Document/#/zh_CN/dev/mission?id=mission%e8%af%a6%e7%bb%86%e4%bb%8b%e7%bb%8d
开发文档这里讲从 Mission 类继承。 
```
from source.mission.mission import Mission
class MissionMain(Mission): ...
```
我尝试了一下发现在同目录下有同名的包和模块时，python优先导入了包，然后报错了
百度搜到了相同的结果，所以感觉可能是个bug？
-https://blog.csdn.net/UZDW_/article/details/131745636
![image](https://github.com/user-attachments/assets/443646dd-f8f1-4a71-af6c-7d0768a55908)

**Comment by infstellar** [comment]
好像没遇到过，但是mission这个包似乎没有用，可以直接删掉（）
