### ISSUE TITLE
策略组是4个角色通用的吗？

### ISSUE THREAD

**Issue by Xwquannnnn** [infstellar/genshin_impact_assistant#18]
刻晴有重击
e?e.e:none;q?q:none;#@e?a~:none

钟离没有重击
q?q:none;e?e~:none

但是实际开始的时候钟离会重击，跟刻晴一样e之后重击三下

队伍配置
[1.txt](https://github.com/infstellar/genshin_impact_assistant/files/10283852/1.txt)

**Comment by infstellar** [comment]
是bug，有时候虽然没有切换角色但也会执行策略组，之后会修

**Comment by infstellar** [comment]
修啦(￣▽￣)ﾉ
