### ISSUE TITLE
國際服支持

### ISSUE THREAD

**Issue by Small-Ku** [infstellar/genshin_impact_assistant#19]
https://github.com/infstellar/genshin_impact_assistant/blob/819d842ce5f09425b8a167b26eee1a06ecb87927/source/interaction_background.py#L28
國際服用的話是"GenshinImpact.exe"
改成以下模樣應該就可以了
```Python
process_name = ("YuanShen.exe", "GenshinImpact.exe")
// ...
            winname = get_active_window_process_name()
            if winname not in process_name:
```

**Comment by infstellar** [comment]
感谢(｀・ω・´) 目前正在做国际服和英文语言的支持

**Comment by Small-Ku** [comment]
加油！d(\`･∀･)b
請問Commit訊息是有在參考[Conventional Commit](https://www.conventionalcommits.org/zh-hans/v1.0.0/)嗎？
下次感謝訊息可以嘗試放到body裡，讓Commit主題短一點w
在footer之類的位置加上如`fixes: #19`或者`closes: #19`，相關的keywords可以看[這篇](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)，當commit進到main branch的時候應該就會自動關掉issue了。

**Comment by infstellar** [comment]
Thanks♪(･ω･)ﾉ Git用得比较少，我去看一下
