### ISSUE TITLE
路径记录问题

### ISSUE THREAD

**Issue by Zhuazizizi** [infstellar/genshin_impact_assistant#191]
新版本的路径记录会出现一种很奇怪的折返路线，比如我控制人物直线跑（中途没有偏移镜头没有转身），生成的路线总会在其中某段出现一个折反，我导出到空荧酒馆后发现路线是这样的，基本上记录出来的全是这样的，一步三回头。
![image](https://github.com/user-attachments/assets/a8e6199e-4211-4661-a94a-8397e665de4e)
![image](https://github.com/user-attachments/assets/c524b08a-9fe4-42b1-8c7d-7e1ca3d11669)
还有个问题是在使用自己的自定义任务时有时会遇见这个提示。
2024-08-13 15:37:13.886 | WARNING  | source.funclib.combat_lib:get_characters_name:354 - get characters name fail, retry 1
2024-08-13 15:37:14.886 | WARNING  | source.funclib.combat_lib:get_characters_name:354 - get characters name fail, retry 2
任务开始后一直在原地慢慢转动镜头转一次提示一次。
还有个小建议是，能不能减少输出在gui上的日志类型，不知道是不是我电脑性能问题，在记录路径这种高频输出日志的情况下我的界面经常会卡死，之前版本是在浏览器上的卡死我可以刷新，现在版本的界面我没法刷新了。

**Comment by infstellar** [comment]
发一下记录的json看看

**Comment by infstellar** [comment]
点优化路径再导出有没有效果

**Comment by infstellar** [comment]
你在开发群里吗，这里发图片有点费劲

**Comment by Zhuazizizi** [comment]
> 你在开发群里吗，这里发图片有点费劲

原来还有群，优化路线是有效果的，开的够高的话，只是有些我想绕一下石头或怪的点容易被优化掉，
