### ISSUE TITLE
保持角色站場

### ISSUE THREAD

**Issue by Small-Ku** [infstellar/genshin_impact_assistant#20]
請問有辦法讓角色在元素爆發生效期間不切人嗎？
賽諾和一斗的元素爆發都是在生效時增強他們的普攻/重擊傷害，一旦切人就失去效用。

**Comment by infstellar** [comment]
可以看看[策略关键字](https://github.com/infstellar/genshin_impact_assistant/blob/main/doc/combat_assi.md)中的`#@q?A:B`这一项
