### ISSUE TITLE
似乎在寻找委托时出错

### ISSUE THREAD

**Issue by UBC2008** [infstellar/genshin_impact_assistant#202]
一直在反复点击如图位置
![屏幕截图 2024-09-07 102558](https://github.com/user-attachments/assets/09967104-996b-4674-aae1-4c6219b18f0f)

请问可否使用冒险之书的方式定位委托？

**Comment by infstellar** [comment]
是不是无边框窗口？要在设置里改一下

**Comment by UBC2008** [comment]
无边框窗口和全屏都试过了，今天又复现了

https://github.com/user-attachments/assets/8e8ad64a-d09a-464f-b60f-ddb3f63fa39d

![屏幕截图 2024-09-08 123731](https://github.com/user-attachments/assets/146f87e0-3119-430d-af1d-f86aa7f31b3f)

**Comment by UBC2008** [comment]
[2024-09-08.log](https://github.com/user-attachments/files/16920805/2024-09-08.log)

**Comment by infstellar** [comment]
无边框窗口和全屏是一个类型；要在设置里修改
https://genshinimpactassistant.github.io/GIA-Document/#/zh_CN/jijiking
