### ISSUE TITLE
UI界面检测失败

### ISSUE THREAD

**Issue by Asakushen** [infstellar/genshin_impact_assistant#22]
日志：[2023-01-25.log](https://github.com/infstellar/genshin_impact_assistant/files/10491971/2023-01-25.log)
截图不放了，一步步来的重装过一次还是报UI界面检测失败，后台能关的软件全都关了，也没开滤镜。
系统;WIN11

**Comment by infstellar** [comment]
win11寄了 悲

**Comment by Asakushen** [comment]
大悲

**Comment by infstellar** [comment]
Win11有能截图的方法了
按这个issue操作
https://github.com/GengGode/cvAutoTrack/issues/9
