### ISSUE TITLE
运行时报错 我的python版本3.9 会不会是版本问题

### ISSUE THREAD

**Issue by luojueling** [infstellar/genshin_impact_assistant#25]
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by infstellar** [comment]
OMP：错误#15：初始化libiomp5md.dll，但发现libiomp5md.dll已经被初始化。
OMP: 提示 这意味着OpenMP运行时的多个副本已经被链接到程序中。这很危险，因为它可能会降低性能或导致不正确的结果。最好的办法是确保只有一个OpenMP运行时被链接到程序中，例如，避免在任何库中静态链接OpenMP运行时。作为一个不安全的、不被支持的、没有记录的变通方法，你可以设置环境变量KMP_DUPLICATE_LIB_OK=TRUE来允许程序继续执行，但是这可能会导致崩溃或者默默地产生不正确的结果。欲了解更多信息，请参见http://www.intel.com/software/products/support/。

可以尝试使用3.9版本python，但对稳定性不做任何保证。
