### ISSUE TITLE
PYWEBIO界面打不开，内部错误

### ISSUE THREAD

**Issue by pein0saga** [infstellar/genshin_impact_assistant#27]
An internal error occurred in the application

甚至连个错误代码都没有

**Comment by pein0saga** [comment]
https://github.com/pywebio/PyWebIO/issues/446#issuecomment-1208057532

https://github.com/pywebio/PyWebIO/discussions/454

**Comment by Legend-Recalls** [comment]
same with me gia 0.6 but gia webui v0.5.0

**Comment by infstellar** [comment]
在我这里重现不了，试试使用installer_config_cn.json来安装

**Comment by infstellar** [comment]
我尽量快点更新下个版本(

**Comment by yes5528876** [comment]
改用installer_config_cn.json仍然不行QQ

**Comment by yes5528876** [comment]
我暫時發現的解法:
1.將giainstaller.py裡的main部分註解掉一部分


![image](https://user-images.githubusercontent.com/55228217/226950399-cbb4e333-6fd6-4c6b-bb73-3e9cb98823a3.png)


2.將pages.py的CollectorSettingPage類__init__修改
```python
self.collection_names = load_json("ITEM_NAME.json", "assets\\POI_JSON_API\\$lang$")
```
改成
```python
self.collection_names = load_json("ITEM_NAME.json", "assets\\POI_JSON_API\\zh_CN")
```
![image](https://user-images.githubusercontent.com/55228217/226951353-76101815-53b7-496b-a84e-ebd570ab3e40.png)

**Comment by Lutra-Fs** [comment]
我也是ITEM_NAME not found. 把config的GLOBAL_LANG覆盖成zh_CN解决了。系统是中文，unsure about why it use en_US in $lang. 没细看代码

**Comment by infstellar** [comment]
oh 英文的采集点坐标没有加进去 我先设定默认中文吧

**Comment by infstellar** [comment]
解决惹 GIAv0.7.1
