### ISSUE TITLE
好像是在设置语言的时候出错了

### ISSUE THREAD

**Issue by wang-zh** [infstellar/genshin_impact_assistant#30]
![image](https://user-images.githubusercontent.com/39694902/227748591-55eeff03-e7c1-403c-bc99-0e191937e326.png)

![image](https://user-images.githubusercontent.com/39694902/227748618-2195008e-eef0-45e9-bf5d-5f986f2f33e1.png)

**Comment by infstellar** [comment]
重装试试?(

**Comment by wang-zh** [comment]
还是有这个问题

**Comment by infstellar** [comment]
系统版本是多少

**Comment by infstellar** [comment]
可能有一个路径没有写好 等会修

**Comment by wang-zh** [comment]
版本	Windows 10 家庭中文版
版本号	22H2
安装日期	‎2022/‎1/‎9
操作系统内部版本	19045.2728
体验	Windows Feature Experience Pack 120.2212.4190.0

**Comment by infstellar** [comment]
win10不会有问题鸭 怪事(

**Comment by infstellar** [comment]
可能是gettext.py GB2312字符集和UTF-8字符集冲突，已修复
