### ISSUE TITLE
Fail to get capture: shape

### ISSUE THREAD

**Issue by Dr-WeiAL** [infstellar/genshin_impact_assistant#31]
[2023-04-03.log](https://github.com/infstellar/genshin_impact_assistant/files/11133126/2023-04-03.log)
一直在报错

**Comment by infstellar** [comment]
2000x1125是什么分辨率⊙(・◇・)？
看过[FAQ](https://github.com/infstellar/genshin_impact_assistant/blob/main/doc/FAQ.md)了吗

**Comment by infstellar** [comment]
有没有多显示器

**Comment by Dr-WeiAL** [comment]
有的，笔记本外界了一块屏幕
![image](https://user-images.githubusercontent.com/47446553/229425659-31c4d358-6406-49cd-bdb7-dd2782e98bee.png)
2是显示器，1是笔记本屏幕

**Comment by infstellar** [comment]
原神的分辨率要是1920x1080鸭 不管全屏还是窗口化
