### ISSUE TITLE
功能建议：自动使用脆弱树脂和控制台控制挑战次数

### ISSUE THREAD

**Issue by lhllhx** [infstellar/genshin_impact_assistant#5]
自动使用脆弱树脂 
实现思路： config可以设置 是否在树脂不足时自动使用脆弱树脂

控制台控制挑战次数 
实现思路： config挑战次数设置为零时 在程序初始化前询问挑战次数 就不用每次改文件了

**Comment by infstellar** [comment]
控制台控制挑战次数可以有(￣▽￣)~
脆弱树脂可以手动用一大堆再刷吧(

**Comment by lhllhx** [comment]
确实可以 当时没想到٩( 'ω' )و
