### ISSUE TITLE
请求优化自动战斗

### ISSUE THREAD

**Issue by gongfuture** [infstellar/genshin_impact_assistant#51]
以胡行钟夜为例
1.角色定位
钟离作为护盾角色，无论是否护盾还存在，都将立即上场释放护盾，将打断循环
或许可以改成持续时间结束补护盾？
2.优先级
个人感觉优先级系统过于单线程，先不论夜兰行秋，就钟离胡桃而言，若钟1胡4，夜行23，则实战中胡桃基本上只能戳两枪，若钟4胡1，夜行依旧，则开场不会套盾，若钟1胡2，夜行34，则夜行有时还没挂水胡桃又上场了
而且配置文档中有看到四种角色定位，而webui只有两种（还有一种甚至空白，我不知道是不是我的问腿）
3.策略组
当我发现以上问题想通过策略组解决的时候，发现策略组仅支持对角色自身进行策略调整。是否可以支持例如放完大切换指定角色此类策略设计？

**Comment by gongfuture** [comment]
只是给出建议哈，要是叫我写我也不大会QWQ

**Comment by infstellar** [comment]
1. 立即上场是为了活着，之前并没有这个机制但是主C老是死
2. webui可能忘记加了(
2. 3. 现在的策略组确实有点不够灵活，未来可能会增加一种对单个语句进行trigger和priority配置的高级战斗策略，但是现在主要在做自动每日委托() 所以可能要等1.0之后再加了。
