### ISSUE TITLE
风龙废墟处自动寻路错误

### ISSUE THREAD

**Issue by gongfuture** [infstellar/genshin_impact_assistant#53]
事情发生在我使用自动每日，一个战斗委托刷在风龙废墟附近，它就传送到风龙废墟内的那个小传送点，然后顺着风龙废墟内墙爬
![image](https://github.com/infstellar/genshin_impact_assistant/assets/60888755/9537da65-ed7e-4710-b600-6c2038f3fabc)
![image](https://github.com/infstellar/genshin_impact_assistant/assets/60888755/abedd9c0-59cd-4588-ac30-9d7a23fe60fb)
ran然后判定这个任务失败就跳过去了
可否将此锚点和神像还有周本传送点设置为黑名单，基本没有刷新在里面的委托

**Comment by infstellar** [comment]
是的,下次更新修复.

**Comment by infstellar** [comment]
已更新,如果问题已修复请关闭issue~

**Comment by gongfuture** [comment]
今天没有刷到风龙废墟任务，暂时无法验证

**Comment by gongfuture** [comment]
确认修复
