### ISSUE TITLE
是否有支持Apple Silicon的Playcover版原神的计划？

### ISSUE THREAD

**Issue by TankNee** [infstellar/genshin_impact_assistant#58]
playcover版的原神设置好映射之后，按键基本和pc端一致，或者可以模拟一个xbox手柄，用手柄输入替换原本的键盘输入？

**Comment by infstellar** [comment]
看了一下,playcover版的原神的UI好像是移动端的.
- 移动端跟PC端的操作逻辑不同
- 目前所有的交互操作都基于win32api

所以目前应该没有支持的计划.
