### ISSUE TITLE
急冻树附近“持盾的危机”每日委托寻路错误

### ISSUE THREAD

**Issue by gongfuture** [infstellar/genshin_impact_assistant#60]
<img width="292" alt="Snipaste_2023-06-04_11-42-16" src="https://github.com/infstellar/genshin_impact_assistant/assets/60888755/83f3ee48-4457-46ec-8df0-45733f564798">

他会优先选择左上防的锚点，经过下面遗迹固定触发冰深渊法师，然后先爬上山再跳下来，最后卡在一个上面有突起的柱子上
录屏：
链接：https://pan.baidu.com/s/1jWT7ibGsxDLf90kOFLGrFA?pwd=bblt 
提取码：bblt 
复制这段内容后打开百度网盘手机App，操作更方便哦
log：
[log.txt](https://github.com/infstellar/genshin_impact_assistant/files/11644717/log.txt)

**Comment by gongfuture** [comment]
如果将秘境类传送点也并入搜索范围是否可行？

**Comment by infstellar** [comment]
应该指的是副本类传送点. 副本类传送点有些比较离谱.
这个问题应该可以通过[TLN](https://github.com/GenshinImpactAssistant/GIA-Document/blob/main/zh_CN/dev/TianLiPositioningSystem.md)解决.
