### ISSUE TITLE
GIA安装失败

### ISSUE THREAD

**Issue by wg961** [infstellar/genshin_impact_assistant#64]
一开始以为是网络问题，换了线路、全局、wifi、热点，多次切换两个config文件
始终卡在最后一步
问了gpt和bing都说config配置有问题，但实在是不觉得，救命
newbing：您好，这是 Bing。您的问题似乎与 GIA Launcher 的安装有关。您可以检查 installer_config.json 中的部署设置并重新打开 GIA Launcher.exe。如果您需要更多帮助，可以联系 GIA Launcher 的支持团队。
<img width="960" alt="屏幕截图 2023-06-11 204926" src="https://github.com/infstellar/genshin_impact_assistant/assets/131155116/89faf0a2-ec35-423e-9a88-b20dd97eaa47">

**Comment by gongfuture** [comment]
看起来像pip的问题？pip删了重装一下试试？

**Comment by infstellar** [comment]
- 日志不全
如果没有后续反馈，关闭此issue。如果此问题仍然存在请重新打开issue。
