### ISSUE TITLE
可以增加显示各个地区的自动每日任务的完成度吗？

### ISSUE THREAD

**Issue by l497996153** [infstellar/genshin_impact_assistant#69]
比如：
各地区自动每日任务完成度：
蒙德：xx/xx
璃月：yy/yy
稻妻：zz/zz
......

**Comment by infstellar** [comment]
每日任务是指每日委托吗？
现在和将来应该都只支持蒙德的每日委托。

**Comment by l497996153** [comment]
> 每日任务是指每日委托吗？ 现在和将来应该都只支持蒙德的每日委托。
对，好的

**Comment by l497996153** [comment]
> 每日任务是指每日委托吗？
> 
> 现在和将来应该都只支持蒙德的每日委托。
蒙德有些跑腿每日委托又臭又长，这种以后会完成吗？

**Comment by infstellar** [comment]
> > 每日任务是指每日委托吗？
> > 现在和将来应该都只支持蒙德的每日委托。
> > 蒙德有些跑腿每日委托又臭又长，这种以后会完成吗？

可能吧(
跑腿任务技术难度比较小，但是脚本代码量大一些
