### ISSUE TITLE
面向 ChatGPT 的疑难任务解决方案

### ISSUE THREAD

**Issue by KumaTea** [infstellar/genshin_impact_assistant#71]
> 注：这不是一条 feature request, 仅为思路启发

在遇到未收录的任务 ([任务列表](https://wiki.biligame.com/ys/%E5%A7%94%E6%89%98%E4%BB%BB%E5%8A%A1)) 时，可以尝试询问 ChatGPT 或其他大语言模型，获取是否能够简单处理 (还是必须摇人)

首先，把每日任务的当前步骤分为以下几项：

* 与敌人战斗
* 与NPC聊天
* 收集物品
* 前往目的地
* 以上都不是

然后再向 ChatGPT 提供当前的任务提示，如果属于上述内容，可尝试执行。

## 测试

以下是我的一些 test cases

* 开场白

User: 

> The steps of daily tasks in game Genshin Impact can be classified into 4 categories:
>
> 　
>
> A. combat with enemies
>
> B. chat with NPC
>
> C. collect items
>
> D. go to destination
>
> E. none of the above
>
> 　
>
> Note: a step can be only one or a combination of multiple types. Do you understand? (answer only yes/no)

ChatGPT:

> Yes, I understand.

1.

> Now I'm doing a task called "餐品订单", the instruction of current step is "把餐费交给餐馆莎拉".
> 
> Please answer the type(s) of current step.

> Based on the given instruction, the type of the current step would be:
> 
> B. Chat with NPC

(正确)

<details>
  <summary>2 - 8</summary>
  

2.

> Now I'm doing a task called "安全运输法则", the instruction of current step is "护送货运气球安全抵达目的地".
> 
> Please answer the type(s) of current step.

> Based on the given instruction, the type of the current step "护送货运气球安全抵达目的地" in the task "安全运输法则" would fall under category D: go to destination.

(错误，应为AD)

3.

> Now I'm doing a task called "来自冬天的故事", the instruction of current step is "获得丘丘人暴徒战利品".
>
> Please answer the type(s) of current step.

> Based on the given instruction, the type of the current step would be:
>
> C. Collect items

(错误，应为A或AC)

4.

> Now I'm doing a task called "钥匙是易丢品", the instruction of current step is "用元素视野寻找钥匙".
> 
> Please answer the type(s) of current step.

> Based on the given instruction, the type of the current step would be "C. collect items" since the task is to use elemental sight to search for a key.

(正确)

5.

> Now I'm doing a task called "趁鲜花气息逗留", the instruction of current step is "前往雪山的七天神像附近放置包裹".
> 
> Please answer the type(s) of current step.

> Based on the given instruction, the type of the current step would be:
> 
> D. Go to destination

(部分正确，应为DC)

6.

> Now I'm doing a task called "危险运输现象", the instruction of current step is "摧毁史莱姆气球".
> 
> Please answer the type(s) of current step.

> The type of the current step "摧毁史莱姆气球" in the task "危险运输现象" would be A. combat with enemies.

(正确)

7.

> Now I'm doing a task called "雷野险踪", the instruction of current step is "调查雷元素异常点".
> 
> Please answer the type(s) of current step.

> Based on the given instruction, the current step "调查雷元素异常点" in the task "雷野险踪" can be classified as category C: collect items.

(正确)

8.

> Now I'm doing a task called "菇测高度", the instruction of current step is "完成连续跳跃挑战".
> 
> Please answer the type(s) of current step.

> Based on the provided instruction "完成连续跳跃挑战" (which translates to "Complete the continuous jumping challenge"), the type of the current step would be "E. none of the above" since it does not fall into any of the four given categories (combat with enemies, chat with NPC, collect items, go to destination).

(正确)

</details>

## 优缺点

* 优点：减少干预频次
* 缺点：
* * 不一定理解正确
* * 难以指令 ChatGPT 只输出答案不输出原因
* * 不是很理解这是不定项选择题

**Comment by infstellar** [comment]
有点意思诶
如果把NPC的对话内容和委托描述都输入进去，选择题改成程序可以直接执行的操作，应该是有可行性的
