### ISSUE TITLE
动态链接库(DLL)初始化例程失败。

### ISSUE THREAD

**Issue by xunhualing** [infstellar/genshin_impact_assistant#84]
[log.txt](https://github.com/infstellar/genshin_impact_assistant/files/12039858/log.txt)

**Comment by infstellar** [comment]
可能电脑的C++运行库等没有装全

**Comment by xunhualing** [comment]
> 可能电脑的C++运行库等没有装全

我重新安装了一遍c++常用运行库也还是这样
出现上面那问题，程序就直接关闭了，要重新点luanch.exe

**Comment by infstellar** [comment]
不清楚是哪个dll缺失，实在不行试试用Visual Studio装C++全家桶把

**Comment by infstellar** [comment]
找到问题了，你的CPU可能不支持AVX指令集，我会尝试寻找解决方案

**Comment by infstellar** [comment]
需要重新编译fastdeploy并安装。
参考 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/cpu.md
对于无AVX指令集CPU，按如下设置参数：
```powershell
set ENABLE_ORT_BACKEND=ON
set ENABLE_PADDLE_BACKEND=OFF
set ENABLE_OPENVINO_BACKEND=OFF
set ENABLE_VISION=ON
set ENABLE_TEXT=OFF
```

**Comment by xunhualing** [comment]
> 需要重新编译fastdeploy并安装。 参考 https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/cpu.md 对于无AVX指令集CPU，按如下设置参数：
> 
> ```powershell
> set ENABLE_ORT_BACKEND=ON
> set ENABLE_PADDLE_BACKEND=OFF
> set ENABLE_OPENVINO_BACKEND=OFF
> set ENABLE_VISION=ON
> set ENABLE_TEXT=OFF
> ```

大佬牛皮，好了

**Comment by aiden-leong** [comment]
binary: https://github.com/aiden-leong/FastDeploy/releases/tag/cpu-non-avx
