### ISSUE TITLE
卡在地图界面

### ISSUE THREAD

**Issue by BakaJzon** [infstellar/genshin_impact_assistant#86]
可以进入原神，进入后不管什么操作都会模拟按m键进入地图，然后卡住

**Comment by xunhualing** [comment]
我是每日任务启动时开开地图就会卡在地图界面，打完一把秘境后就会卡在圣遗物那里

**Comment by infstellar** [comment]
发一下日志

**Comment by xunhualing** [comment]
> 发一下日志

[log (2).txt](https://github.com/infstellar/genshin_impact_assistant/files/12067874/log.2.txt)
![IMG_20230717_173543](https://github.com/infstellar/genshin_impact_assistant/assets/44472453/0f98d937-2daa-4522-a63f-3acab80bc4af)
![DG(`7PD81E{}ANLHI{QB AI](https://github.com/infstellar/genshin_impact_assistant/assets/44472453/21beaee1-de9b-430c-819d-369cb11a7c58)
启动每日委托任务后，就卡这了。
还有秘境打完后不会重开下一把

**Comment by BakaJzon** [comment]
> 发一下日志

我开了debug模式之后，log里面也只有隔一两秒截一次屏。什么输出也没有
如果我选择传送或者esc，他就会弹出一个UIgoto回到地图

状态永远是加载中或not register yet。

**Comment by infstellar** [comment]
> > 发一下日志
> 
> [log (2).txt](https://github.com/infstellar/genshin_impact_assistant/files/12067874/log.2.txt) ![IMG_20230717_173543](https://user-images.githubusercontent.com/44472453/253903351-0f98d937-2daa-4522-a63f-3acab80bc4af.jpg) ![DG(`7PD81E{}ANLHI{QB AI](https://user-images.githubusercontent.com/44472453/253903887-21beaee1-de9b-430c-819d-369cb11a7c58.png) 启动每日委托任务后，就卡这了。 还有秘境打完后不会重开下一把

需要日志文件 这个没用 在logs文件夹里

**Comment by xunhualing** [comment]
> 发一下日志

[2023-07-17.log](https://github.com/infstellar/genshin_impact_assistant/files/12079426/2023-07-17.log)

**Comment by SMARK2022** [comment]
同样也是这个问题，log中也是到按下m之后就不动了，关闭地图后会自动打开，但不会进一步操作。
详细log中无报错信息提示，也是按的要求设置

**Comment by zxccqwcas** [comment]
我也有这类的问题，但是不是按下m就不动了，而是会点不到传送点，会点在下面一点点的地方，刚好点不到传送点。

**Comment by infstellar** [comment]
> > 发一下日志
> 
> [2023-07-17.log](https://github.com/infstellar/genshin_impact_assistant/files/12079426/2023-07-17.log)

可能是ocr识别失败，发一下大地图界面的截图看看

**Comment by infstellar** [comment]
> 同样也是这个问题，log中也是到按下m之后就不动了，关闭地图后会自动打开，但不会进一步操作。 详细log中无报错信息提示，也是按的要求设置

打开新的issue，提交日志

**Comment by xunhualing** [comment]
![image](https://github.com/infstellar/genshin_impact_assistant/assets/44472453/5dafebe7-2190-483c-ad6c-00495ae0f819)


> > > 发一下日志
> > 
> > 
> > [2023-07-17.log](https://github.com/infstellar/genshin_impact_assistant/files/12079426/2023-07-17.log)
> 
> 可能是ocr识别失败，发一下大地图界面的截图看看

**Comment by xunhualing** [comment]
> > > 发一下日志
> > 
> > 
> > [2023-07-17.log](https://github.com/infstellar/genshin_impact_assistant/files/12079426/2023-07-17.log)
> 
> 可能是ocr识别失败，发一下大地图界面的截图看看

![image](https://github.com/infstellar/genshin_impact_assistant/assets/44472453/0acdc283-0694-4867-8e07-39bac47e5c71)

**Comment by infstellar** [comment]
> > > > 发一下日志
> > > 
> > > 
> > > [2023-07-17.log](https://github.com/infstellar/genshin_impact_assistant/files/12079426/2023-07-17.log)
> > 
> > 
> > 可能是ocr识别失败，发一下大地图界面的截图看看
> 
> ![image](https://user-images.githubusercontent.com/44472453/254896636-0acdc283-0694-4867-8e07-39bac47e5c71.png)

看日志是选择区域（右下角按钮）的OCR识别错误，截一下那个页面的图片看看

**Comment by xunhualing** [comment]
![image](https://github.com/infstellar/genshin_impact_assistant/assets/44472453/c0b29083-4221-43a8-b0f3-82fffc76ab51)


> > > > > 发一下日志
> > > > 
> > > > 
> > > > [2023-07-17.log](https://github.com/infstellar/genshin_impact_assistant/files/12079426/2023-07-17.log)
> > > 
> > > 
> > > 可能是ocr识别失败，发一下大地图界面的截图看看
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/44472453/254896636-0acdc283-0694-4867-8e07-39bac47e5c71.png)
> 
> 看日志是选择区域（右下角按钮）的OCR识别错误，截一下那个页面的图片看看

**Comment by infstellar** [comment]
怪事，看起来没问题鸭
有今天的日志记录吗

**Comment by SMARK2022** [comment]
我今天断点调试找到原因了，问题出在定位系统的map.py中 一个检测大地图缩放的方法中。方法的操作为：1.点击切换区域2.点击层岩巨渊（该方法有误，在国家中肯定无法找到，导致陷入死循环）3.再次点击切换区域4.点击璃月国然后我这个函数调到最后也没有发现调整缩放的实现这个检查缩放的方法我看没有实现相应的功能啊（不知道是不是github与gitee更新问题，还是说确实没有实现）-------- 原始邮件 --------发件人： infstellar ***@***.***>日期： 2023年7月20日周四 22:05收件人： infstellar/genshin_impact_assistant ***@***.***>抄送： SMARK ***@***.***>, Comment ***@***.***>主    题： Re: [infstellar/genshin_impact_assistant] 卡在地图界面 (Issue #86)
怪事，看起来没问题鸭
有今天的日志记录吗

**Comment by infstellar** [comment]
> 2.点击层岩巨渊（该方法有误，在国家中肯定无法找到，导致陷入死循环）
为什么无法找到呢？

**Comment by infstellar** [comment]
> 我今天断点调试找到原因了，问题出在定位系统的map.py中 一个检测大地图缩放的方法中。方法的操作为：1.点击切换区域2.点击层岩巨渊（该方法有误，在国家中肯定无法找到，导致陷入死循环）3.再次点击切换区域4.点击璃月国然后我这个函数调到最后也没有发现调整缩放的实现这个检查缩放的方法我看没有实现相应的功能啊（不知道是不是github与gitee更新问题，还是说确实没有实现）-------- 原始邮件 --------发件人： infstellar ***@***.***>日期： 2023年7月20日周四 22:05收件人： infstellar/genshin_impact_assistant ***@***.***>抄送： SMARK ***@***.***>, Comment ***@***.***>主 题： Re: [infstellar/genshin_impact_assistant] 卡在地图界面 (Issue #86) 怪事，看起来没问题鸭 有今天的日志记录吗 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

> 2.点击层岩巨渊（该方法有误，在国家中肯定无法找到，导致陷入死循环）

为什么无法找到呢？

**Comment by infstellar** [comment]
调整缩放的实现就是切换层岩巨渊

**Comment by BakaJzon** [comment]
```
2023-07-23 12:58:26.041 | INFO     | source.task.task_manager:loop:145 - task LaunchGenshinTask end.
2023-07-23 12:58:26.042 | INFO     | source.task.task_manager:start_stop_task:113 - 任务结束
[ WARN:1@221.059] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('F:/GIMAP.png'): can't open/read file: check file path/integrity
2023-07-23 12:58:26.607 | INFO     | source.api.pdocr_api:__init__:50 - Creating PaddleOCRFastDeploy object: D:\python-git-program-launcher\repositories\GIA_Launcher_Download_Lib\assets\PPOCRModels\en_US
[INFO] fastdeploy/runtime/runtime.cc(273)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
[INFO] fastdeploy/runtime/runtime.cc(273)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
2023-07-23 12:58:27.217 | INFO     | source.api.pdocr_api:__init__:59 - created DBDetector and Recognizer. cost 0.61
2023-07-23 12:58:27.218 | INFO     | source.api.pdocr_api:__init__:62 - created PPOCRv3. cost 0.0
2023-07-23 12:58:27.219 | INFO     | source.api.pdocr_light:<module>:5 - created pdocr. cost 0.61 second.
2023-07-23 12:58:27.823 | INFO     | source.mission.mission_template:_init_sub_threading:79 - Thread-43 PUO has been initialized and started.
2023-07-23 12:58:27.825 | INFO     | source.task.task_manager:start_stop_task:104 - 任务LeyLineOutcropTask启动。
2023-07-23 12:58:28.259 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_bigmap
1
1
1
1
1
1
2023-07-23 13:00:00.303 | INFO     | source.task.task_manager:loop:145 - task LeyLineOutcropTask end.
2023-07-23 13:00:00.304 | INFO     | source.task.task_manager:start_stop_task:113 - 任务结束
2023-07-23 13:00:00.308 | INFO     | source.task.task_manager:loop:147 - all task end.
2023-07-23 13:00:00.818 | INFO     | source.pickup.pickup_operator:run:86 - 停止自动拾取
1
```
地图全解锁，但是序章没过

**Comment by infstellar** [comment]
> > 可以进入原神，进入后不管什么操作都会模拟按m键进入地图，然后卡住
> 
> ```
> 2023-07-23 12:58:26.041 | INFO     | source.task.task_manager:loop:145 - task LaunchGenshinTask end.
> 2023-07-23 12:58:26.042 | INFO     | source.task.task_manager:start_stop_task:113 - 任务结束
> [ WARN:1@221.059] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('F:/GIMAP.png'): can't open/read file: check file path/integrity
> 2023-07-23 12:58:26.607 | INFO     | source.api.pdocr_api:__init__:50 - Creating PaddleOCRFastDeploy object: D:\python-git-program-launcher\repositories\GIA_Launcher_Download_Lib\assets\PPOCRModels\en_US
> [INFO] fastdeploy/runtime/runtime.cc(273)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
> [INFO] fastdeploy/runtime/runtime.cc(273)::fastdeploy::Runtime::CreatePaddleBackend     Runtime initialized with Backend::PDINFER in Device::CPU.
> 2023-07-23 12:58:27.217 | INFO     | source.api.pdocr_api:__init__:59 - created DBDetector and Recognizer. cost 0.61
> 2023-07-23 12:58:27.218 | INFO     | source.api.pdocr_api:__init__:62 - created PPOCRv3. cost 0.0
> 2023-07-23 12:58:27.219 | INFO     | source.api.pdocr_light:<module>:5 - created pdocr. cost 0.61 second.
> 2023-07-23 12:58:27.823 | INFO     | source.mission.mission_template:_init_sub_threading:79 - Thread-43 PUO has been initialized and started.
> 2023-07-23 12:58:27.825 | INFO     | source.task.task_manager:start_stop_task:104 - 任务LeyLineOutcropTask启动。
> 2023-07-23 12:58:28.259 | INFO     | source.ui.ui:ui_goto:76 - UI goto page_bigmap
> 1
> 1
> 1
> 1
> 1
> 1
> 2023-07-23 13:00:00.303 | INFO     | source.task.task_manager:loop:145 - task LeyLineOutcropTask end.
> 2023-07-23 13:00:00.304 | INFO     | source.task.task_manager:start_stop_task:113 - 任务结束
> 2023-07-23 13:00:00.308 | INFO     | source.task.task_manager:loop:147 - all task end.
> 2023-07-23 13:00:00.818 | INFO     | source.pickup.pickup_operator:run:86 - 停止自动拾取
> 1
> ```
> 
> 地图全解锁，但是序章没过

序章是什么？地图切换有没有层岩巨渊的选项？
需要日志文件，控制台的信息不能看出太多问题

**Comment by BakaJzon** [comment]
序章就是新手魔神任务（蒙德），但是我现阶段所有的七天神像都解锁了。
有层岩巨渊，已解锁地下矿区的入口，但地下矿区等级不够。
[2023-07-23.log](https://github.com/infstellar/genshin_impact_assistant/files/12139029/2023-07-23.log)

![图片](https://github.com/infstellar/genshin_impact_assistant/assets/55239052/7b6eb358-e14e-4289-bf47-86c2a9fd16dd)

主要做每日委托用，和进度应该没多大关系。

**Comment by infstellar** [comment]
> 序章就是新手魔神任务（蒙德），但是我现阶段所有的七天神像都解锁了。 有层岩巨渊，已解锁地下矿区的入口，但地下矿区等级不够。 [2023-07-23.log](https://github.com/infstellar/genshin_impact_assistant/files/12139029/2023-07-23.log)
> 
> ![图片](https://user-images.githubusercontent.com/55239052/255403374-7b6eb358-e14e-4289-bf47-86c2a9fd16dd.png)
> 
> 主要做每日委托用，和进度应该没多大关系。

没解锁螺旋秘境吗

**Comment by infstellar** [comment]
好像应该叫深境螺旋

**Comment by BakaJzon** [comment]
刚解锁，现在是这样。
![图片](https://github.com/infstellar/genshin_impact_assistant/assets/55239052/d238ad3a-10ee-4e53-8b12-a9159833da9a)
[2023-07-23.log](https://github.com/infstellar/genshin_impact_assistant/files/12139593/2023-07-23.log)

**Comment by infstellar** [comment]
要让层岩巨渊的选项出现在右侧的选择栏里
你是怎么玩原神的，为啥进度这么怪⊙(・◇・)？

**Comment by TimyWimey** [comment]
也就是得先过好多的主线，才能使用这个？我也是主线没过完，卡在地图界面。

**Comment by TimyWimey** [comment]
> 也就是得先过好多的主线，才能使用这个？我也是主线没过完，卡在地图界面。

在FAQ里找到说要解锁`层岩巨渊 地下矿区`，要先完成璃月的主线，我还没玩到这

**Comment by BakaJzon** [comment]
已经成老登了（悲）

总而言之，需要解锁`层岩巨渊 地下矿区` ，就是完成璃月主线和对应世界任务，才能使用委托功能。（不过现在都有历练点了）
不知道另一个错误 OCR识别 的有没有修复。。
