### ISSUE TITLE
为啥每日委托到目的地之后不会自动战斗？

### ISSUE THREAD

**Issue by zxccqwcas** [infstellar/genshin_impact_assistant#90]

**Comment by infstellar** [comment]
?

**Comment by zxccqwcas** [comment]
[2023-07-22.log](https://github.com/infstellar/genshin_impact_assistant/files/12135564/2023-07-22.log)
是因为识别不到角色吗？
我配队是这样子的
![QQ截图20230722103716](https://github.com/infstellar/genshin_impact_assistant/assets/94770524/7d353644-f748-4f85-bbd5-aeeb23ea6f8b)

**Comment by infstellar** [comment]
新版本修复了不支持Kirara的问题 ~（理论上）~

**Comment by zxccqwcas** [comment]
大佬你好，那个清每日委托，进别人的世界的话，是能够自动寻路的，能通过一定设置，达成自动战斗吗？
毕竟可以通过进小号刷战斗委托的方式，完成每天4个每日委托的日常，一个自抽号也就一块钱而已
